CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    SALARY INT
);

INSERT INTO EMPLOYEE VALUES (1,'RAHUL','IT',60000);
INSERT INTO EMPLOYEE VALUES (2,'PRIYA','HR',50000);
INSERT INTO EMPLOYEE VALUES (3,'AMAN','FINANCE',70000);

CREATE VIEW EMPLOYEE_VIEW AS
SELECT EMP_ID, EMP_NAME, DEPARTMENT
FROM EMPLOYEE;

CREATE ROLE ANALYST;

GRANT SELECT ON EMPLOYEE_VIEW TO ANALYST;
